variable "aws_region" {
  description = "AWS region"
  default     = "us-east-1"
}

data "aws_availability_zones" "available" {}

variable "aws_profile" {
  default = "personal"
}
variable "private_key_path" {}
variable "public_key_path" {
  default = "~/.ssh/id_rsa.pub"
}
variable "network_address_space" {
  default = "10.1.0.0/16"
}
variable "public_subnet1_address_space" {
  default = "10.1.0.0/24"
}
variable "public_subnet2_address_space" {
  default = "10.1.1.0/24"
}

variable "private_subnet1_address_space" {
  default = "10.1.0.0/24"
}
variable "private_subnet2_address_space" {
  default = "10.1.1.0/24"
}

/* Packer baked AMI */
variable "ami" {
  description = "AMI Generated by Packer"
}
